**NUMPY**

1-Numpy provides efficient storage (numbers rather than lists in python also space bchata h)
2-it also provide better ways of handling data for  processing
3- It is fast
4- It is easy to Learn
5- Numpy uses relatively less memory to store data and can manage memory smartly

No Pointers here




In [1]:
import numpy as np

In [ ]:
myarr= np.array([[3,6,32,7]],np.int8) #8bytes means 2digit or increase the size

In [ ]:
myarr

array([[ 3,  6, 32,  7]], dtype=int8)

In [ ]:
myarr[0,1]

6

In [ ]:
myarr.shape

(1, 4)

In [ ]:
myarr.dtype

dtype('int8')

In [ ]:
#can search for numpy type reference

In [ ]:
myarr[0,1]=45

In [ ]:
myarr

array([[ 3, 45, 32,  7]], dtype=int8)

In [ ]:
# numpy array creation method  or array creations method in numpy

In [ ]:
#  ***Array  : Conversion from other python structures

In [ ]:
listarray = np.array([[1,2,4],[5,8,5],[0,3,0]])


In [ ]:
listarray

array([[1, 2, 4],
       [5, 8, 5],
       [0, 3, 0]])

In [ ]:
listarray.dtype

dtype('int64')

In [ ]:
listarray .shape

(3, 3)

In [ ]:
listarray.size

9

In [ ]:
np.array({34,23,23})

array({34, 23}, dtype=object)

In [ ]:
#integer and array  is in m=float all time

In [ ]:
zeros=np.zeros((2,5))

In [ ]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
zeros.shape

(2, 5)

In [ ]:
zeros.dtype

dtype('float64')

In [4]:
rng=np.arange(15)

In [5]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [3]:
lspace=np.linspace(1,5,12) #for linearly spaced

In [ ]:
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [ ]:
lspace=np.linspace(1,4,4)

In [ ]:
lspace

array([1., 2., 3., 4.])

In [ ]:
emp=np.empty((4,6))  #give random array of this type

In [ ]:
emp

array([[-0.25, -0.5 ,  0.  , -0.25,  0.25, -0.5 ],
       [ 0.5 , -0.25,  0.25,  0.  ,  0.5 ,  0.25],
       [ 0.25,  0.5 ,  0.  ,  0.25, -0.25,  0.5 ],
       [-0.5 ,  0.25, -0.25,  0.  , -0.5 , -0.25]])

In [ ]:
emp_like=np.empty_like(lspace) #purane array ka size copy krke ik nya array bna deta h

In [ ]:
emp_like

array([1., 2., 3., 4.])

In [ ]:
ide=np.identity(45) #give identity matrix

In [ ]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [ ]:
ide.shape

(45, 45)

In [ ]:
arr = np.arange(99)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [ ]:
#if i want to reshape this
arr=arr.reshape(3,33)  #but yeh number multiply krke vhi anne chhye

In [ ]:
arr  #this is not change here

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [ ]:
arr=arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [ ]:
arr.shape

(3, 33)

In [ ]:
x=[[1,2,3],[4,5,6],[7,1,0]]

In [ ]:
ar= np.array(x)

In [ ]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [ ]:
ar.sum(axis=0)

array([12,  8,  9])

In [ ]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [ ]:
#numpy have some attributes or methods as well

In [ ]:
ar.T #transpose original array into vice versa

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [ ]:
ar.flat #give iterator from here

In [ ]:
for i in ar.flat:
  print(i)

1
2
3
4
5
6
7
1
0


In [ ]:
ar.ndim #ndim: shows number of dimensions

2

In [ ]:
ar.size

9

In [ ]:
ar.nbytes #returns the total number of bytes consumed by the elements of a NumPy array

72

In [ ]:
one = np.array([1,3,4,634,2])

In [ ]:
one.argmax() #gives the index of maximum element

3

In [ ]:
one.argmin()

0

In [ ]:
one.argsort() #gives the index of sorted array

array([0, 4, 1, 2, 3])

In [ ]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [ ]:
ar.argmin()

8

In [ ]:
ar.argmax()

6

In [ ]:
ar.argmax(axis=0)

array([2, 1, 1])

In [ ]:
ar.argmax(axis=1)

array([2, 2, 0])

In [ ]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

In [ ]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]])

In [ ]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [ ]:
ar.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [ ]:
ar.reshape(9,)

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [ ]:
#in numpy we can use matrix operation
ar2=np.array([[1, 4, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [ ]:
ar+ar2

array([[ 2,  6,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [ ]:
#not applicable in list
[324,34]+[34,546]

[324, 34, 34, 546]

In [ ]:
ar * ar2

array([[ 1,  8,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [ ]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [ ]:
ar.sum()

29

In [ ]:
ar.min()

0

In [ ]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [ ]:
np.where(ar>5) #will return arrays tuple

(array([1, 2]), array([2, 0]))

In [ ]:
type(np.where(ar>5))

tuple

In [ ]:
np.count_nonzero(ar)

8

In [ ]:
np.nonzero(ar)  #can see indexes where non zeros elements are present

(array([0, 0, 0, 1, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1]))

In [ ]:
ar[1,2]=0

In [ ]:
import sys

In [ ]:
py_ar = [0,4,55,2]

In [ ]:
np_ar = np.array(py_ar)

In [ ]:
#size for both
sys.getsizeof(1)*len(py_ar)

112

In [ ]:
np_ar.itemsize * np_ar.size

32

In [ ]:
np_ar.tolist()

[0, 4, 55, 2]